# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno and run tests across stable builds on Windows, Ubuntu and macOS.
# For more information see: https://github.com/denolib/setup-deno

name: Deno-daily

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 12 * * *'

jobs:
  test:
    runs-on: ${{ matrix.os }} # runs a test on Ubuntu, Windows and macOS

    strategy:
      matrix:
        deno: ["v1.8.3"]
        os: [macOS-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Setup repo
        uses: actions/checkout@v2
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

      - name: Setup Deno
        uses: denolib/setup-deno@c7d7968ad4a59c159a777f79adddad6872ee8d96
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        with:
          deno-version: ${{ matrix.deno }} # tests across multiple Deno versions

      - name: Cache Dependencies
        run: deno cache server/lib/deps.ts
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

      - name: Run Tests
        run: deno test --allow-net --allow-read --allow-run server/test/daily/index.ts
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
